### ISSUE TITLE
oidc-register fails under Python 3.5

### ISSUE THREAD

**Issue by ncoghlan** [puiterwijk/flask-oidc#12]
I'm attempting to adapt the Hubs OIDC code for use in Anitya, and ran into the following error trying to run oidc-register under a Python 3.5 venv: 

```
$ oidc-register --debug https://iddev.fedorainfracloud.org/ http://localhost:5000
Error discovering OP information
the JSON object must be str, not 'bytes'
ERROR:oidc-register:Error caught when discovering OP information:
Traceback (most recent call last):
  File "/home/ncoghlan/.virtualenvs/anitya/lib/python3.5/site-packages/flask_oidc/registration_util.py", line 65, in main
    OP = discovery.discover_OP_information(args.provider_url)
  File "/home/ncoghlan/.virtualenvs/anitya/lib/python3.5/site-packages/flask_oidc/discovery.py", line 43, in discover_OP_information
    return json.loads(content)
  File "/usr/lib64/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by puiterwijk** [comment]
Hi, thanks for the report.
I think I'll go for the _json_loads utility function, as that sounds more reliable in the longterm since it's easier to add to other places.

**Comment by ncoghlan** [comment]
Would it be possible to get a 1.0.5 release with this change?

I've reached a point where my work https://github.com/fedora-infra/anitya/issues/329 appears to be hitting it.

**Comment by puiterwijk** [comment]
There is now a 1.1.0 release with this change.
