### ISSUE TITLE
userinfo_uri is not required... its optional but the library requires it...

### ISSUE THREAD

**Issue by pdoronila** [puiterwijk/flask-oidc#13]
Could there be option to configure the use of the userinfo_uri or not to use it? 

CoreOS OpenId Connect Provider (https://github.com/coreos/dex) didn't implement the userinfo endpoint because it's optional. 

In order to get this library to work with coreos openId connect provider, I had to comment out lines 188 thru 199
(https://github.com/puiterwijk/flask-oidc/blob/master/flask_oidc/__init__.py#L188-L199) for it to work with coreos openid connect provider.

**Comment by puiterwijk** [comment]
This has been fixed with d3bec40.
