### ISSUE TITLE
PLEASE depreciate the puiterwijk/flask-oidc repo

### ISSUE THREAD

**Issue by isedwards** [puiterwijk/flask-oidc#161]
The top hit for "flask oidc" in search engines is the v1.1 docs here:
    https://flask-oidc.readthedocs.io/en/latest/

The GitHub link in the docs is to this repo (the original) where the README has no mention of the new maintained version.

The README even claims "This project is in active development", yet the [fedora-infra](https://github.com/fedora-infra/flask-oidc) version has successfully taken over the [PyPI listing](https://pypi.org/project/flask-oidc/).

Is it possible to:
1. Remove the old readthedocs page (or give control to the fedora-infra team)
2. Update the README in this repository to point to the new location of the project
3. Archive this repo so that people don't make PRs

I nearly ruled out Flask-OIDC as a solution until I saw the [Is this repo dead?](https://github.com/puiterwijk/flask-oidc/issues/146) issue and saw that fedora-infra now maintaining the official PyPI listing.

**Comment by abompard** [comment]
I've updated the README, unfortunately I don't have access to the readthedocs account. @puiterwijk could you add me in the admins please?

**Comment by isedwards** [comment]
@abompard - just checking whether @puiterwijk replied and granted readthedocs access?

A message at the top of https://flask-oidc.readthedocs.io/ would be really helpful.

**Comment by abompard** [comment]
Still nothing, unfortunately.
