### ISSUE TITLE
Document (or point to documentation) how to use the API tokens

### ISSUE THREAD

**Issue by jeremycline** [puiterwijk/flask-oidc#18]
Right now, the documentation mentions [an accept_token decorator](http://flask-oidc.readthedocs.io/en/latest/?badge=latest#resource-server), but provides no details on how a client should use this. I assume this is some sort of standard, but there's no indication of that in the docs.

**Comment by puiterwijk** [comment]
The tokens accepted are following the OAuth2 bearer token standard: https://tools.ietf.org/html/rfc6750.
The short overview is to do one of the following:
- access_token in form fields
- HTTP Authorization header with value "Bearer <token>"

**Comment by puiterwijk** [comment]
http://flask-oidc.readthedocs.io/en/latest/?badge=latest#flask_oidc.OpenIDConnect.accept_token
