### ISSUE TITLE
Is there any documentation for this somewhere?

### ISSUE THREAD

**Issue by altryne** [puiterwijk/flask-oidc#2]
I'd love to see a basic example or a documentation of using this

**Comment by SteelPangolin** [comment]
Thanks for asking! There isn't a completely worked example or docs yet, but there's a very tiny app in the test suite based on Flask's app factory pattern:
https://github.com/SteelPangolin/flask-oidc/blob/master/tests/app.py
https://github.com/SteelPangolin/flask-oidc/blob/master/tests/test_flask_oidc.py#L66
http://flask.pocoo.org/docs/0.10/patterns/appfactories/

**Comment by hught** [comment]
I've gotten it where it calls back after prompting for authentication.

How to fetch the user details though...?

**Comment by puiterwijk** [comment]
I have taken over maintenance of this project, and will write documentation in the next few days.

I have now added a basic example in the main directory as example.py.
This will show how to get the users' email address, which at this moment is the only piece of information retrieved.

I'm working on generalizing this.

**Comment by puiterwijk** [comment]
There is now documentation for v1.0: http://flask-oidc.readthedocs.io/en/latest/.
