### ISSUE TITLE
Make JSON rendering configurable for error responses

### ISSUE THREAD

**Issue by ncoghlan** [puiterwijk/flask-oidc#25]
Combining flask-oidc with Flask-RESTful for Anitya, we've run into a problem where the error responses that flask-oidc pre-renders to JSON strings are then rendered *again* as encoded JSON text responses by Flask-RESTful: https://github.com/release-monitoring/anitya/issues/443

The lowest impact solution that occurred to me is to have `accept_token` accept an extra parameter (defaulting to `json.dumps`) that defines how the error rendering happens.

**Comment by ncoghlan** [comment]
https://github.com/puiterwijk/flask-oidc/pull/26 adds a new `render_errors` parameter to `accept_token`, as well as corresponding test cases for the `render_errors=None` case.

**Comment by puiterwijk** [comment]
So, the problem with this way is that we are currently sending JSON objects as they are defined in the OAuth2 specification, to improve compatibility.
If we were to allow anything, it would require users of this function to figure out how they are supposed to encode it themselves.

**Comment by ncoghlan** [comment]
I'm fine with using a boolean toggle instead (for lazy-encoding-or-not). The key problem with the status quo is that it's incompatible with frameworks like Flask-RESTful that expect a dict object that the framework then encodes.

**Comment by ncoghlan** [comment]
https://github.com/puiterwijk/flask-oidc/pull/27 is an alternative PR that just lets users turn off the eager error rendering for compatibility with REST frameworks that automatically encode all responses as JSON.

**Comment by puiterwijk** [comment]
#27 has now been merged.
