### ISSUE TITLE
Token introspection uses a wrong value for token_type_hint

### ISSUE THREAD

**Issue by thomasdarimont** [puiterwijk/flask-oidc#35]
The `_get_token_info`method of the `OpenIDConnect` class currently uses 'Bearer' as 
the value for the `token_type_hint` parameter.
See: https://github.com/puiterwijk/flask-oidc/blob/b5c9c1e2128e4d56e0457b431d5b0dbbac58e2d3/flask_oidc/__init__.py#L748

According to the spec, only `access_token` or `refresh_token` are allowed as values for the `token_type_hint` parameter.

See:
https://tools.ietf.org/html/rfc7662

> Values for this field are defined in the "OAuth Token Type Hints" registry defined
> in OAuth Token Revocation [RFC7009].

The `typ` field in the JWT must be mapped to the following `token_type_hint` values:
* typ: Bearer --> access_token
* typ: Refresh --> refresh_token

Another option may be to not set the `token_type_hint` parameter at all.

See also:
https://connect2id.com/products/server/docs/api/token-introspection

I stumbled upon this issue whilst trying to use [Keycloak](http://www.keycloak.org/) in combination with flask-oidc. When I send the token info request without the `token_type_hint` parameter (by patching the flask-oidc lib) then the token info can be retrieved from Keycloak `token_introspection_endpoint`.

**Comment by thomasdarimont** [comment]
... as a workaround I needed to patch `flask_oidc/__init__.py`, a better way would be to have support for provider specific configuration.

with:
```python
...
    def _get_token_info(self, token):
        # We hardcode to use client_secret_post, because that's what the Google
        # oauth2client library defaults to
#        request = {'token': token,
#                   'token_type_hint': 'Bearer'}

# work around for https://github.com/puiterwijk/flask-oidc/issues/35
        request = {'token': token}
        headers = {'Content-type': 'application/x-www-form-urlencoded'}
...
```

**Comment by puiterwijk** [comment]
You were correct, thanks for the correction.
