### ISSUE TITLE
The token is not refreshed after about 72 minutes

### ISSUE THREAD

**Issue by abompard** [puiterwijk/flask-oidc#47]
I don't know if it's the expected behaviour or not...
I have this flask app (Fedora Hubs) that is designed to be left open for a while and auto-refreshes the page contents. To avoid the user being disconnected, I have setup a call to a `/ping` URL that the Javascript makes every minute. This `/ping` url is not decorated, but since it's inside the Flask app and flask_oidc is used, it should benefit from the `before_request` hook that is automatically setup.

This hook calls `authenticate_or_redirect()` which should automatically refresh the OIDC token using the refresh token, except it apparently never happens, or does not work. I'll try to print some stuff to see what's wrong here.

**Comment by abompard** [comment]
I have news! On login a cookie is generated with the `exp` field set to about 10 minutes later. When that time arrives, the `authenticate_or_redirect()` method rightfully refreshes the token, but the next `exp` date set is *one hour* later. When that time arrives, it's too late and a `itsdangerous.SignatureExpired` exception is raised in `_get_cookie_id_token`, causing the redirection to login.

**Comment by abompard** [comment]
OK, so if i change the default `expires_in` when instantiating `TimedJSONWebSignatureSerializer` in `OpenIDConnect.init_app()` to something higher than an hour (I've set 7200s), it all works fine. The expiry time set by the server is still 3600s but this time it does not cause an invalidation in the cookie signature.

**Comment by bkabrda** [comment]
Hi, I think I'm experiencing the same issue. It seems that if a user doesn't do anything for 60 minutes, they get logged out. A solution to this (I'm not sure if it's the "right" solution) would probably be to set `expires_in` for `TimedJSONWebSignatureSerializer` to value of `OIDC_ID_TOKEN_COOKIE_TTL`. It feels a bit hackish, but seems to work for me.
