### ISSUE TITLE
Multiple audiences and not authorized party with list of one audience.

### ISSUE THREAD

**Issue by TheKigen** [puiterwijk/flask-oidc#58]
Hi,

The error is in function _is_id_token_valid().  If the id_token['aud'] is a list of one it treats it as though it was a list of multiple audiences and tries to require the azp field.

This needs to be corrected with a check for the len() if aud is a list.

Thanks.

**Comment by TheKigen** [comment]
`        if isinstance(id_token['aud'], list):
            # step 3 for audience list
            if self.flow.client_id not in id_token['aud']:
                logger.error('We are not a valid audience')
                return False
            # step 4
            if 'azp' not in id_token and len(id_token['aud']) > 1:
                logger.error('Multiple audiences and not authorized party')
                return False`

**Comment by puiterwijk** [comment]
Hi, thanks for the report.
This has been fixed in e638787ca3bb787a7b3b4a74fae23cd915fbd1d1.
