### ISSUE TITLE
Resource server documentation fix

### ISSUE THREAD

**Issue by cjmartian** [puiterwijk/flask-oidc#80]
In the Resource server paragraph, the docs state:

"Also, if you have implemented an API that can should be able to accept tokens
issued by the OpenID Connect provider, just decorate those API functions with. . . "

I believe this should read:

"Also, if you have implemented an API that should be able to accept tokens
issued by the OpenID Connect provider, just decorate those API functions with. . ."

I would be happy to make this change if it is needed.

**Comment by svintit** [comment]
If you want this resolved i'm maintaining a fork of this with some added extensibility. Feel free to open a PR/issue here:
- https://github.com/svintit/flask-oidc-ext/pulls
